all:
	g++ -c pang.cpp Game.cpp MainMenu.cpp SplashScreen.cpp VisibleGameObject.cpp PlayerPaddle.cpp
	g++ pang.o Game.o MainMenu.o SplashScreen.o VisibleGameObject.o PlayerPaddle.o -o pang -lsfml-graphics -lsfml-window -lsfml-system
	./pang
